{
 "title": "Breeze - Smart Environmental Sensor Hub",
 "time": { "from": "2021-04-24T12:33:39.523Z", "to": "2021-04-24T13:03:22.346Z" },
 "panels": [
  {
   "title": "AccelerometerX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerX\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "AccelerometerX" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AccelerometerY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerY\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "AccelerometerX" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AccelerometerZ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerZ\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "AccelerometerX" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality PM 2.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerZ\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "PM2.5" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality PM 1.0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerZ\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "PM1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality PM 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerZ\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "PM10" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UltraViolet A Radiaton",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"AccelerometerZ\" FROM \"breeze\"",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning Detection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"Lightning\" FROM \"breeze\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Lightning" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Earthquake Detection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "breeze",
     "query": "SELECT \"Lightning\" FROM \"breeze\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Lightning" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}